# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build Reverse Example

# events that trigger workflows
on:
  push: # everytime someone pushes to master branch, trigger workflow
    branches: [ master ]
  pull_request: # everytime PR created with master branch as target, trigger workflow
    branches: [ master ]

# one of more jobs (set of actions)
jobs:

  build: # groups set of steps
    # runs steps on same environment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # checkout repo, "actions" path have predefined steps https://github.com/actions

    # "uses": selects an action
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    # "run": runs CMD command
    - name: Build
      run: |
        go version
        go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: kkaryl/demo-app:latest