# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

# events that trigger workflows
on:
  push: # everytime someone pushes to master branch, trigger workflow
    branches: [ master ]
  pull_request: # everytime PR created with master branch as target, trigger workflow
    branches: [ master ]

# one of more jobs (set of actions)
jobs:

  build: # groups set of steps
    # runs steps on same environment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # checkout repo, "actions" path have predefined steps https://github.com/actions

    # "uses": selects an action
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    # "run": runs CMD command
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...